apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-app
  namespace: argocd
spec:
  project: default
  # First Source (Frontend from Git Repository)
  source:
    repoURL: https://github.com/OpsMx/cnoe.git
    targetRevision: main
    path: Argocd/argocd-apps-srcs/argocd-re-src/single-helm-src
    helm:
      releaseName: frontend-app
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  # Second Source (Backend from a Different Git Repository)
  sources:
    - repoURL: https://github.com/OpsMx/cnoe.git
      targetRevision: main
      path: Argocd/argocd-apps-srcs/argocd-re-src/single-git-src
  
  # Optional third source (Database from a Helm chart)
  sources:
    - repoURL: https://opsmx.github.io/cnoe-helm
      chart: cnoe-charts
      targetRevision: 0.1.0
      helm:
        releaseName: postgresql
        values: |
          postgresqlPassword: "mysecretpassword"
          postgresqlDatabase: "mydatabase"
  destination:
    server: https://kubernetes.default.svc
    namespace: multisource
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
