apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default  # Change to your desired namespace if necessary
spec:
  replicas: 1  # Number of replicas (pods) to deploy
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Using the latest Nginx image from Docker Hub
          ports:
            - containerPort: 80  # Exposing port 80 on the container
