apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-kustomize-helm
spec:
  entrypoint: deploy-pipeline
  templates:
  - name: deploy-pipeline
    steps:
    - - name: kustomize-deploy
        template: kustomize-deploy
    - - name: helm-deploy
        template: helm-deploy

  - name: kustomize-deploy
    container:
      image: "kustomize/kustomize:v4.5.7"
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Deploying with Kustomize..."
          kustomize build /workspace/kustomize-dir | kubectl apply -f -

  - name: helm-deploy
    container:
      image: "alpine/helm:3.6.3"
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Deploying with Helm..."
          helm upgrade --install my-release /workspace/helm-chart --namespace helm-kustomize-naveen
