apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-git-app-dev
  namespace: argocd
spec:
  project: dev-environment
  source:
    repoURL: https://github.com/OpsMx/argo-sample-apps.git
    path: apps-resources/single-git-resources
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: proj2-single-git-dev-env
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
