apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-git-guestbook-img-app
  namespace: argocd
spec:
  project: cnoe-proj-argocd-apps
  source:
    repoURL: https://github.com/OpsMx/argo-sample-apps.git
    path: Argocd/argocd-apps-srcs/argocd-re-src/single-git-src
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: git-src-app-nav
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
