apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app-1
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: "https://github.com/OpsMx/argo-sample-apps.git"  # Correct URL format without space
    targetRevision: HEAD
    path: apps-resources/app-of-apps-resources/child-app1
    helm:
      valueFiles:
        - values.yaml  # Specify your Helm values file here
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
