apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-applicationset-frontend-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: list-appset-first-app-apline-img-nav
            repoURL: 'https://github.com/OpsMx/cnoe.git'
            targetRevision: 'HEAD'
            path: Argocd/argocd-apps-srcs/argocd-re-src/Generator-appset-resources/list-appset-resources/single-list-appset-src
          - name: list-appset-second-app-nginx-img-nav
            repoURL: 'https://github.com/OpsMx/cnoe.git'
            targetRevision: 'HEAD'
            path: Argocd/argocd-apps-srcs/argocd-re-src/Generator-appset-resources/list-appset-resources/two-list-appset-src
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: frontend-apps
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'list-appset-app-nav'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
