# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: opsmxgitpush
spec:
  # Manually created the service and updated the ingress
  github:
    opsmxpush:
      repositories:
        - owner: opsmx
          names:
            - cnoe  #For testing, we can give multiple repos
            - ssdgate
      webhook:
        endpoint: "/cnoe-events"
        port: "13000"
        method: "POST"
      events:
        - "push"
        #- "*"
      webhookSecret:  # Need to create this secret in argo-events namespace for the trigger to work
        name: opsmx-git-webhook-secret
        key: secret
      insecure: false
      active: true
      contentType: "json"

