apiVersion: v1
kind: Service
metadata:
  labels:
    controller: eventsource-controller
    eventsource-name: opsmxgitpush
    owner-name: opsmxgitpush
  name: opsmxgitpush-eventsource-svc
  namespace: argo-events
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - name: opsmxgitpush
    port: 13000
    protocol: TCP
    targetPort: 13000
  selector:
    controller: eventsource-controller
    eventsource-name: opsmxgitpush
    owner-name: opsmxgitpush
  sessionAffinity: None
  type: ClusterIP
