apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  annotations:
  name: opsmxgit
  namespace: argo-events
spec:
  dependencies:
  - eventName: opsmxpush # "push" event filtered in the eventsource config
    eventSourceName: opsmxgitpush
    name: opsmxpush-generic
    filters:
      data:
      - path: body.ref
        type: string
        value:
        - "refs/heads/main"   # Trigger for push only on main
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
  - template:
      k8s:
        operation: create
        parameters:
        - dest: spec.arguments.parameters.0.value  # Replace "message", which is the 1st argument-param below
          src:
            dataKey: body.repository.name
            #dataKey: body.ref
            #dataKey: body.commits.0.message
            dependencyName: opsmxpush-generic
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: opsmx-
            spec:
              arguments:
                parameters:
                - name: message
                  value: WILLBEREPLACED
              entrypoint: whalesay
              templates:
              - container:
                  args:
                  - '{{inputs.parameters.message}}'
                  command:
                  - cowsay
                  image: docker/whalesay:latest
                inputs:
                  parameters:
                  - name: message
                name: whalesay
      name: opsmxpush-workflow
