apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/git-repo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
