apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  annotations:
  name: webhook
  namespace: argo-events
spec:
  service:
    metadata:
      annotations:
        foo: bar
      labels:
        foo: bar
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    webhook:
      endpoint: /webhook
      method: POST
      port: "12000"
      url: ""
